languageCode = "en-us"
title = "Anydot's blog"
baseurl = "http://anydot.in/"
theme = "hugo-theme-geppaku"

[author]
    name = "Premysl Hruby"
    twitter = "anydot"
    github = "anydot"
    linkedin = "přemysl-hrubý-aa340539"

[params]
    disqusShortname = "ranydot"
