name: github pages

on:
  push:
    branches:
    - source

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.1.0
      with:
        submodules: true

    - name: Run Hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        image: ext-alpine
        env: production

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./public